use std::collections::BTreeMap;
use std::fmt::Write as _;

use ledgerkit_core::{AccountId, LedgerSnapshot, Transaction};

use crate::{ExportError, Exporter};

/// Beancount exporter: commodity/open directives, metadata, skip duplicates.
#[derive(Debug, Default, Clone)]
pub struct BeancountExporter;

pub(crate) fn active_transactions(snapshot: &LedgerSnapshot) -> Vec<&Transaction> {
    let mut txs: Vec<&Transaction> = snapshot
        .transactions
        .iter()
        .filter(|t| t.duplicate_of.is_none())
        .collect();
    txs.sort_by(|a, b| {
        a.date
            .cmp(&b.date)
            .then_with(|| a.id.to_string().cmp(&b.id.to_string()))
    });
    txs
}

/// Beancount requires `Assets:` / `Expenses:` style names.
pub fn bean_account(account: &AccountId) -> String {
    account
        .as_str()
        .split(':')
        .map(|seg| {
            let mut chars = seg.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(":")
}

fn escape_bean_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

impl Exporter for BeancountExporter {
    fn id(&self) -> &'static str {
        "beancount"
    }

    fn export(&self, snapshot: &LedgerSnapshot) -> Result<String, ExportError> {
        let txs = active_transactions(snapshot);
        let mut commodities: BTreeMap<String, String> = BTreeMap::new();
        let mut opens: BTreeMap<String, String> = BTreeMap::new();

        for tx in &txs {
            let date = tx.date.format("%Y-%m-%d").to_string();
            for posting in &tx.postings {
                let c = posting.commodity.as_str().to_string();
                commodities
                    .entry(c)
                    .and_modify(|d| {
                        if date.as_str() < d.as_str() {
                            *d = date.clone();
                        }
                    })
                    .or_insert_with(|| date.clone());
                let acct = bean_account(&posting.account);
                opens
                    .entry(acct)
                    .and_modify(|d| {
                        if date.as_str() < d.as_str() {
                            *d = date.clone();
                        }
                    })
                    .or_insert_with(|| date.clone());
            }
        }

        let mut out = String::from("; Generated by LedgerKit (deterministic)\n");
        if let Some(op) = commodities.keys().next() {
            let _ = writeln!(out, "option \"operating_currency\" \"{op}\"");
        }
        out.push('\n');

        for (code, date) in &commodities {
            let _ = writeln!(out, "{date} commodity {code}");
        }
        if !commodities.is_empty() {
            out.push('\n');
        }

        for (acct, date) in &opens {
            let _ = writeln!(out, "{date} open {acct}");
        }
        if !opens.is_empty() {
            out.push('\n');
        }

        for tx in txs {
            let payee = escape_bean_string(&tx.payee);
            let narration = tx
                .narration
                .as_deref()
                .filter(|s| !s.is_empty())
                .map(escape_bean_string);
            match narration {
                Some(n) => {
                    let _ = writeln!(
                        out,
                        "{} * \"{}\" \"{}\"",
                        tx.date.format("%Y-%m-%d"),
                        payee,
                        n
                    );
                }
                None => {
                    let _ = writeln!(out, "{} * \"{}\"", tx.date.format("%Y-%m-%d"), payee);
                }
            }
            let _ = writeln!(out, "  id: \"{}\"", tx.id);
            if let Some(batch) = tx.import_batch_id {
                let _ = writeln!(out, "  import_batch: \"{batch}\"");
            }
            for tag in &tx.tags {
                if let Some(cat) = tag.strip_prefix("category:") {
                    let _ = writeln!(out, "  category: \"{}\"", escape_bean_string(cat));
                }
            }
            for posting in &tx.postings {
                let _ = write!(
                    out,
                    "  {}  {} {}",
                    bean_account(&posting.account),
                    posting.amount,
                    posting.commodity
                );
                if let Some(memo) = &posting.memo {
                    if !memo.is_empty() {
                        let _ = write!(out, " ; {}", memo.replace('\n', " "));
                    }
                }
                out.push('\n');
            }
            out.push('\n');
        }

        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ledgerkit_core::{
        account_balance, AccountId, Amount, Commodity, LedgerSnapshot, Transaction,
    };
    use pretty_assertions::assert_eq;

    fn cafe() -> Transaction {
        Transaction::transfer(
            chrono::NaiveDate::from_ymd_opt(2026, 1, 3).unwrap(),
            AccountId::new("assets:bank:checking").unwrap(),
            AccountId::new("expenses:food").unwrap(),
            Amount::parse("6.50").unwrap(),
            Commodity::new("USD").unwrap(),
            "STARBUCKS \"STORE\"",
        )
        .unwrap()
    }

    #[test]
    fn bean_account_capitalizes_segments() {
        assert_eq!(
            bean_account(&AccountId::new("assets:bank:checking").unwrap()),
            "Assets:Bank:Checking"
        );
    }

    #[test]
    fn skips_duplicates_and_emits_directives() {
        let mut a = cafe();
        a.tags.push("category:expenses:food".into());
        a.narration = Some("starbucks".into());
        let mut b = cafe();
        b.duplicate_of = Some(a.id);
        let dup_id = b.id;
        let snap = LedgerSnapshot {
            transactions: vec![a.clone(), b],
        };
        let body = BeancountExporter.export(&snap).unwrap();
        assert!(body.contains("option \"operating_currency\" \"USD\""));
        assert!(body.contains("2026-01-03 commodity USD"));
        assert!(body.contains("2026-01-03 open Assets:Bank:Checking"));
        assert!(body.contains("2026-01-03 open Expenses:Food"));
        assert!(body.contains("category: \"expenses:food\""));
        assert!(body.contains("id: "));
        assert!(body.contains("STARBUCKS \\\"STORE\\\""));
        assert_eq!(body.matches("STARBUCKS").count(), 1);
        assert!(!body.contains(&dup_id.to_string()));
        assert_eq!(body, BeancountExporter.export(&snap).unwrap());
        assert_eq!(
            account_balance(
                &snap,
                &AccountId::new("assets:bank:checking").unwrap(),
                &Commodity::new("USD").unwrap(),
            )
            .unwrap()
            .to_string(),
            "-6.50"
        );
    }
}
