use ledgerkit_core::LedgerSnapshot;

use crate::{ExportError, Exporter};

/// Minimal Beancount exporter (Phase 6 deepens commodity directives + metadata).
#[derive(Debug, Default, Clone)]
pub struct BeancountExporter;

impl Exporter for BeancountExporter {
    fn id(&self) -> &'static str {
        "beancount"
    }

    fn export(&self, snapshot: &LedgerSnapshot) -> Result<String, ExportError> {
        let mut out = String::from("; Generated by LedgerKit\n\n");
        for tx in &snapshot.transactions {
            if tx.duplicate_of.is_some() {
                continue;
            }
            out.push_str(&format!(
                "{} * \"{}\"\n",
                tx.date.format("%Y-%m-%d"),
                tx.payee.replace('"', "'")
            ));
            for posting in &tx.postings {
                out.push_str(&format!(
                    "  {}  {} {}\n",
                    posting.account, posting.amount, posting.commodity
                ));
            }
            out.push('\n');
        }
        Ok(out)
    }
}
